/**
 * Auto Feed Data — Curated trending content for the LDMS platform feed
 * Categories: Education News, Job Alerts, Government Schemes, Exam Updates, Teaching Tips, Photos/Community
 * All content mirrors real Indian education ecosystem data with realistic engagement.
 */

// ─── EDUCATION NEWS ───
const EDUCATION_NEWS = [
  {
    category: 'news',
    tag: 'Education News',
    tagColor: 'from-blue-500 to-indigo-600',
    title: 'NEP 2020: States Begin Implementation of 5+3+3+4 Structure',
    summary: 'Multiple states across India have started transitioning to the new educational framework as per the National Education Policy.',
    source: 'Ministry of Education',
    url: 'https://www.education.gov.in/nep',
    author: 'Education Desk',
    authorRole: 'LDMS News',
    likes: '2.4K',
    comments: '187',
    time: '2h ago',
    icon: '🏛️',
  },
  {
    category: 'news',
    tag: 'Education News',
    tagColor: 'from-blue-500 to-indigo-600',
    title: 'CBSE Introduces AI & Coding as Mandatory Subjects from Class 6',
    summary: 'In a landmark decision, CBSE has announced that AI fundamentals and coding will be compulsory subjects starting next academic session.',
    source: 'CBSE Official',
    url: 'https://www.cbse.gov.in/',
    author: 'Education Desk',
    authorRole: 'LDMS News',
    likes: '3.1K',
    comments: '243',
    time: '4h ago',
    icon: '🤖',
  },
  {
    category: 'news',
    tag: 'Education News',
    tagColor: 'from-blue-500 to-indigo-600',
    title: 'Digital Classrooms: 50,000 Government Schools Get Smart Boards',
    summary: 'Under the PM eVIDYA initiative, smart board installations have been completed in government schools across 15 states.',
    source: 'DIKSHA Portal',
    url: 'https://diksha.gov.in/',
    author: 'Education Desk',
    authorRole: 'LDMS News',
    likes: '1.8K',
    comments: '121',
    time: '6h ago',
    icon: '💻',
    image: 'https://images.unsplash.com/photo-1509062522246-3755977927d7?w=600&h=340&fit=crop',
  },
  {
    category: 'news',
    tag: 'Breaking',
    tagColor: 'from-red-500 to-rose-600',
    title: 'UGC Approves Multi-Entry, Multi-Exit System for Higher Education',
    summary: 'Students can now enter and exit degree programs at multiple points, earning certificates and diplomas along the way.',
    source: 'UGC India',
    url: 'https://www.ugc.gov.in/',
    author: 'Education Desk',
    authorRole: 'LDMS News',
    likes: '4.2K',
    comments: '315',
    time: '1h ago',
    icon: '🎓',
  },
  {
    category: 'news',
    tag: 'Education News',
    tagColor: 'from-blue-500 to-indigo-600',
    title: 'NCERT Releases New Textbooks Aligned with NEP 2020 Framework',
    summary: 'Revised textbooks for Classes 1-12 focusing on competency-based learning, critical thinking, and experiential education.',
    source: 'NCERT',
    url: 'https://ncert.nic.in/',
    author: 'Education Desk',
    authorRole: 'LDMS News',
    likes: '2.9K',
    comments: '198',
    time: '5h ago',
    icon: '📚',
  },
  {
    category: 'news',
    tag: 'Education',
    tagColor: 'from-blue-500 to-indigo-600',
    title: 'India Ranks Among Top 5 in Global EdTech Innovation Index',
    summary: 'With over 4,500 EdTech startups, India\'s digital learning ecosystem continues to grow at an unprecedented pace.',
    source: 'NASSCOM',
    url: 'https://nasscom.in/',
    author: 'Education Desk',
    authorRole: 'LDMS News',
    likes: '1.5K',
    comments: '84',
    time: '8h ago',
    icon: '🚀',
  },
]

// ─── JOB ALERTS ───
const JOB_ALERTS = [
  {
    category: 'job',
    tag: 'Naukri Alert',
    tagColor: 'from-emerald-500 to-green-600',
    title: 'DSSSB Teacher Recruitment 2026 — 12,000+ Vacancies',
    summary: 'Delhi Subordinate Services Selection Board has announced massive recruitment for TGT, PGT, and Primary Teacher posts.',
    location: 'Delhi NCR',
    salary: '₹44,900 - ₹1,42,400/month',
    deadline: 'Last Date: May 15, 2026',
    url: 'https://dsssb.delhi.gov.in/',
    author: 'Careers Desk',
    authorRole: 'LDMS Jobs',
    likes: '5.6K',
    comments: '421',
    time: '1h ago',
    icon: '📋',
  },
  {
    category: 'job',
    tag: 'Sarkari Naukri',
    tagColor: 'from-emerald-500 to-green-600',
    title: 'KVS Teacher Vacancy 2026 — PGT, TGT, PRT Posts Open',
    summary: 'Kendriya Vidyalaya Sangathan invites applications for 8,500+ teaching positions across India. B.Ed and CTET qualifications required.',
    location: 'All India',
    salary: '₹35,400 - ₹1,12,400/month',
    deadline: 'Last Date: April 30, 2026',
    url: 'https://kvsangathan.nic.in/',
    author: 'Careers Desk',
    authorRole: 'LDMS Jobs',
    likes: '4.3K',
    comments: '358',
    time: '3h ago',
    icon: '🏫',
  },
  {
    category: 'job',
    tag: 'Private School Jobs',
    tagColor: 'from-teal-500 to-emerald-600',
    title: 'DPS, Ryan & Amity Schools — Hiring 3,000+ Teachers Pan-India',
    summary: 'Top private school chains are hiring Science, Math, English, and Computer Science teachers for the upcoming academic year.',
    location: 'Multiple Cities',
    salary: '₹30,000 - ₹85,000/month',
    deadline: 'Apply by April 20, 2026',
    url: 'https://www.naukri.com/teaching-jobs',
    author: 'Careers Desk',
    authorRole: 'LDMS Jobs',
    likes: '2.1K',
    comments: '153',
    time: '5h ago',
    icon: '🎒',
  },
  {
    category: 'job',
    tag: 'Naukri Alert',
    tagColor: 'from-emerald-500 to-green-600',
    title: 'NVS Teacher Recruitment — 4,600 Posts in Navodaya Schools',
    summary: 'Navodaya Vidyalaya Samiti announces recruitment for PGT, TGT and Miscellaneous category teaching posts.',
    location: 'All India',
    salary: '₹44,900 - ₹1,42,400/month',
    deadline: 'Last Date: May 1, 2026',
    url: 'https://navodaya.gov.in/',
    author: 'Careers Desk',
    authorRole: 'LDMS Jobs',
    likes: '3.7K',
    comments: '289',
    time: '2h ago',
    icon: '📝',
  },
  {
    category: 'job',
    tag: 'EdTech Jobs',
    tagColor: 'from-violet-500 to-purple-600',
    title: 'Unacademy & Vedantu — 2,500+ Online Teaching Roles',
    summary: 'India\'s top EdTech platforms are hiring passionate educators for live classes, content creation, and mentorship roles.',
    location: 'Remote / WFH',
    salary: '₹40,000 - ₹1,20,000/month',
    deadline: 'Rolling Applications',
    url: 'https://www.naukri.com/edtech-teaching-jobs',
    author: 'Careers Desk',
    authorRole: 'LDMS Jobs',
    likes: '1.9K',
    comments: '112',
    time: '7h ago',
    icon: '🖥️',
  },
  {
    category: 'job',
    tag: 'Sarkari Naukri',
    tagColor: 'from-emerald-500 to-green-600',
    title: 'UP TET Qualified — 51,000 Teacher Vacancies in Uttar Pradesh',
    summary: 'The largest teacher recruitment drive in UP history! Assistant Teacher posts for primary and upper primary levels.',
    location: 'Uttar Pradesh',
    salary: '₹36,000 - ₹98,000/month',
    deadline: 'Last Date: June 10, 2026',
    url: 'https://upbasiceduboard.gov.in/',
    author: 'Careers Desk',
    authorRole: 'LDMS Jobs',
    likes: '7.2K',
    comments: '564',
    time: '30m ago',
    icon: '🗳️',
  },
]

// ─── GOVERNMENT SCHEMES ───
const GOVT_SCHEMES = [
  {
    category: 'scheme',
    tag: 'Govt Scheme',
    tagColor: 'from-amber-500 to-orange-600',
    title: 'PM SHRI Schools: ₹27,360 Cr Allocated for Model School Upgrades',
    summary: '14,500+ schools being upgraded to PM SHRI Schools with modern labs, smart classrooms, and sports facilities.',
    url: 'https://www.education.gov.in/pm-shri-schools',
    author: 'Policy Desk',
    authorRole: 'LDMS Gov',
    likes: '3.8K',
    comments: '226',
    time: '4h ago',
    icon: '🇮🇳',
  },
  {
    category: 'scheme',
    tag: 'Govt Scheme',
    tagColor: 'from-amber-500 to-orange-600',
    title: 'Samagra Shiksha Abhiyan: Free Tablets for Teachers in Rural Areas',
    summary: 'Under the revised scheme, 5 lakh teachers in rural government schools will receive tablets with pre-loaded educational content.',
    url: 'https://samagra.education.gov.in/',
    author: 'Policy Desk',
    authorRole: 'LDMS Gov',
    likes: '2.6K',
    comments: '173',
    time: '6h ago',
    icon: '📱',
  },
  {
    category: 'scheme',
    tag: 'Scholarship',
    tagColor: 'from-yellow-500 to-amber-600',
    title: 'National Teacher Award 2026: Nominations Open — ₹50,000 Prize',
    summary: 'Ministry of Education invites nominations for the National Teacher Award recognizing innovative teaching practices.',
    url: 'https://www.education.gov.in/national-award-teachers',
    author: 'Policy Desk',
    authorRole: 'LDMS Gov',
    likes: '1.4K',
    comments: '91',
    time: '8h ago',
    icon: '🏆',
  },
  {
    category: 'scheme',
    tag: 'Govt Update',
    tagColor: 'from-amber-500 to-orange-600',
    title: 'Teachers\' Salary Revision: 7th Pay Commission DA Hike Approved',
    summary: 'Central government approves 4% DA increase for all government teachers effective from January 2026.',
    url: 'https://doe.gov.in/',
    author: 'Policy Desk',
    authorRole: 'LDMS Gov',
    likes: '6.1K',
    comments: '452',
    time: '1h ago',
    icon: '💰',
  },
]

// ─── EXAM UPDATES ───
const EXAM_UPDATES = [
  {
    category: 'exam',
    tag: 'Exam Update',
    tagColor: 'from-rose-500 to-pink-600',
    title: 'CTET December 2026: Registration Opens — New Pattern Released',
    summary: 'CBSE has released the new CTET exam pattern with changes in pedagogy section. Online applications now open.',
    url: 'https://ctet.nic.in/',
    author: 'Exam Desk',
    authorRole: 'LDMS Exams',
    likes: '4.5K',
    comments: '337',
    time: '2h ago',
    icon: '✏️',
  },
  {
    category: 'exam',
    tag: 'Result',
    tagColor: 'from-green-500 to-emerald-600',
    title: 'CBSE Board Results 2026: Pass Percentage Reaches All-Time High',
    summary: '99.2% students pass Class 12, with girls outperforming boys for the 7th consecutive year.',
    url: 'https://results.cbse.nic.in/',
    author: 'Exam Desk',
    authorRole: 'LDMS Exams',
    likes: '8.3K',
    comments: '615',
    time: '45m ago',
    icon: '🎉',
    image: 'https://images.unsplash.com/photo-1523580846011-d3a5bc25702b?w=600&h=340&fit=crop',
  },
  {
    category: 'exam',
    tag: 'Exam Update',
    tagColor: 'from-rose-500 to-pink-600',
    title: 'UGC NET June 2026: Syllabus Revised for Education Paper',
    summary: 'National Testing Agency updates NET syllabus with new topics in Digital Pedagogy and NEP 2020 framework.',
    url: 'https://ugcnet.nta.nic.in/',
    author: 'Exam Desk',
    authorRole: 'LDMS Exams',
    likes: '2.8K',
    comments: '194',
    time: '5h ago',
    icon: '📖',
  },
]

// ─── TEACHING TIPS ───
const TEACHING_TIPS = [
  {
    category: 'tip',
    tag: 'Teaching Tip',
    tagColor: 'from-indigo-500 to-violet-600',
    title: '5 Gamification Strategies That Boosted My Class Engagement by 80%',
    summary: 'How Kahoot quizzes, badge systems, and team challenges transformed student participation in my classroom.',
    author: 'Priya Sharma',
    authorRole: 'Science Teacher, DPS Noida',
    url: 'https://www.edutopia.org/article/gamification-strategies-classroom',
    likes: '1.2K',
    comments: '89',
    time: '3h ago',
    icon: '🎮',
  },
  {
    category: 'tip',
    tag: 'Best Practice',
    tagColor: 'from-cyan-500 to-blue-600',
    title: 'How I Use AI Tools to Create Differentiated Worksheets in Minutes',
    summary: 'Using ChatGPT and LDMS AI Tools, I create 3 difficulty levels of worksheets for each topic — saving me 5 hours weekly.',
    author: 'Rahul Verma',
    authorRole: 'Math Teacher, KV Delhi',
    url: 'https://www.edutopia.org/article/ai-tools-teachers',
    likes: '980',
    comments: '63',
    time: '6h ago',
    icon: '🤖',
  },
  {
    category: 'tip',
    tag: 'Teaching Tip',
    tagColor: 'from-indigo-500 to-violet-600',
    title: 'The "Think-Pair-Share" Method: A Complete Classroom Guide',
    summary: 'This cooperative learning strategy helps introverted students participate and improves critical thinking across all age groups.',
    author: 'Meena Iyer',
    authorRole: 'English Teacher, Amity School',
    url: 'https://www.teachthought.com/pedagogy/think-pair-share/',
    likes: '1.5K',
    comments: '102',
    time: '4h ago',
    icon: '🧠',
    image: 'https://images.unsplash.com/photo-1577896851231-70ef18881754?w=600&h=340&fit=crop',
  },
  {
    category: 'tip',
    tag: 'Innovation',
    tagColor: 'from-fuchsia-500 to-pink-600',
    title: 'Flipped Classroom: Students Watch Lectures at Home, Practice in Class',
    summary: 'I record 10-minute video lessons and use class time for problem-solving, discussions, and hands-on activities.',
    author: 'Amit Joshi',
    authorRole: 'Physics Teacher, NVS',
    url: 'https://www.edutopia.org/article/flipped-classroom',
    likes: '2.1K',
    comments: '147',
    time: '2h ago',
    icon: '🔄',
  },
]

// ─── TRENDING DISCUSSIONS ───
const TRENDING_DISCUSSIONS = [
  {
    category: 'discussion',
    tag: 'Trending',
    tagColor: 'from-orange-500 to-red-600',
    title: 'Should Homework Be Abolished? Educators Across India Share Views',
    summary: 'A heated debate sparked after Finland\'s no-homework policy results were published. Over 50K teachers weigh in.',
    url: 'https://timesofindia.indiatimes.com/education',
    author: 'Community Poll',
    authorRole: 'LDMS Community',
    likes: '6.7K',
    comments: '893',
    time: '30m ago',
    icon: '💬',
  },
  {
    category: 'discussion',
    tag: 'Hot Take',
    tagColor: 'from-orange-500 to-red-600',
    title: 'Board Exams vs Continuous Assessment: Which is Better for Students?',
    summary: 'With NEP pushing for reduced exam stress, educators debate the effectiveness of continuous assessment models.',
    url: 'https://indianexpress.com/section/education/',
    author: 'Community Poll',
    authorRole: 'LDMS Community',
    likes: '4.9K',
    comments: '521',
    time: '1h ago',
    icon: '⚖️',
  },
  {
    category: 'discussion',
    tag: 'Viral',
    tagColor: 'from-red-500 to-rose-600',
    title: 'A Government School Teacher\'s ₹500 Science Lab That Went Viral',
    summary: 'Teacher from Bihar creates a fully functional science lab using household items. The story is inspiring thousands online.',
    url: 'https://www.ndtv.com/education',
    author: 'Community',
    authorRole: 'LDMS Community',
    likes: '11.2K',
    comments: '784',
    time: '15m ago',
    icon: '🔬',
  },
]

// ─── COMMUNITY PHOTO POSTS (using real stock images) ───
const COMMUNITY_PHOTOS = [
  {
    category: 'meme',
    tag: 'Community',
    tagColor: 'from-pink-500 to-rose-600',
    title: 'Our school\'s annual science exhibition was a huge success! 🎉',
    summary: 'Students built working models of renewable energy systems. So proud of our budding scientists! #ScienceExhibition #ProudTeacher',
    image: 'https://images.unsplash.com/photo-1588072432836-e10032774350?w=600&h=400&fit=crop',
    author: 'Ritu Gupta',
    authorRole: 'Science Teacher, DPS Rohini',
    likes: '3.4K',
    comments: '285',
    time: '45m ago',
    icon: '🧪',
  },
  {
    category: 'meme',
    tag: 'Infographic',
    tagColor: 'from-blue-500 to-violet-600',
    title: 'AI in Education: How Top Teachers Are Using Technology in 2026',
    summary: 'From lesson planning to personalized assessments — see how educators are leveraging AI to save time and boost outcomes.',
    image: 'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=600&h=400&fit=crop',
    author: 'EdTech Weekly',
    authorRole: 'LDMS Featured',
    url: 'https://www.edutopia.org/article/ai-tools-teachers',
    likes: '5.1K',
    comments: '342',
    time: '2h ago',
    icon: '🤖',
  },
  {
    category: 'meme',
    tag: 'Motivation',
    tagColor: 'from-amber-500 to-orange-600',
    title: '"The beautiful thing about learning is that nobody can take it away from you." — B.B. King',
    summary: 'Monday motivation for all the amazing educators out there. Share this with someone who inspires you! ✨',
    image: 'https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=600&h=400&fit=crop',
    author: 'LDMS Team',
    authorRole: 'Official',
    likes: '4.8K',
    comments: '196',
    time: '1h ago',
    icon: '✨',
  },
  {
    category: 'meme',
    tag: 'Classroom',
    tagColor: 'from-green-500 to-teal-600',
    title: 'Activity-based learning in action! Students loved today\'s math lab 📐',
    summary: 'Replaced textbook exercises with hands-on measurement activities. The energy in the classroom was incredible!',
    image: 'https://images.unsplash.com/photo-1580582932707-520aed937b7b?w=600&h=400&fit=crop',
    author: 'Sneha Patel',
    authorRole: 'Math Teacher, Ryan International',
    likes: '2.8K',
    comments: '167',
    time: '3h ago',
    icon: '📐',
  },
  {
    category: 'meme',
    tag: 'NEP 2020',
    tagColor: 'from-indigo-500 to-blue-600',
    title: 'NEP 2020 Implementation: What Changed in Our School This Year',
    summary: 'We adopted the 5+3+3+4 structure, multilingual education, and competency-based assessments. Here\'s our experience so far.',
    image: 'https://images.unsplash.com/photo-1497633762265-9d179a990aa6?w=600&h=400&fit=crop',
    author: 'Vikram Singh',
    authorRole: 'Principal, Govt. School Jaipur',
    url: 'https://www.education.gov.in/nep',
    likes: '7.9K',
    comments: '528',
    time: '3h ago',
    icon: '🇮🇳',
  },
  {
    category: 'meme',
    tag: 'Teacher Life',
    tagColor: 'from-purple-500 to-pink-600',
    title: 'End of term report cards done! 156 students — 3 days — 0 sleep 😅',
    summary: 'But seeing their progress over the year makes it all worth it. Every single one of them has grown so much! 💪📚',
    image: 'https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=600&h=400&fit=crop',
    author: 'Kavita Reddy',
    authorRole: 'English Teacher, DAV School',
    likes: '8.7K',
    comments: '671',
    time: '20m ago',
    icon: '📝',
  },
]

// ─── ALL DATA COMBINED ───
export const ALL_AUTO_FEED = [
  ...EDUCATION_NEWS,
  ...JOB_ALERTS,
  ...GOVT_SCHEMES,
  ...EXAM_UPDATES,
  ...TEACHING_TIPS,
  ...TRENDING_DISCUSSIONS,
  ...COMMUNITY_PHOTOS,
]

/**
 * Get a shuffled selection of auto-feed items
 */
export function getAutoFeedItems(count = 10) {
  const shuffled = [...ALL_AUTO_FEED].sort(() => Math.random() - 0.5)
  return shuffled.slice(0, count)
}

/**
 * Get items by category
 */
export function getItemsByCategory(category) {
  return ALL_AUTO_FEED.filter(item => item.category === category)
}

/**
 * Get a single random item
 */
export function getRandomFeedItem() {
  return ALL_AUTO_FEED[Math.floor(Math.random() * ALL_AUTO_FEED.length)]
}

/**
 * Get ticker items
 */
export function getTickerItems(count = 5) {
  const topItems = ALL_AUTO_FEED.filter(item => 
    item.category === 'news' || item.category === 'job' || item.category === 'exam'
  ).sort(() => Math.random() - 0.5)
  return topItems.slice(0, count)
}

export { EDUCATION_NEWS, JOB_ALERTS, GOVT_SCHEMES, EXAM_UPDATES, TEACHING_TIPS, TRENDING_DISCUSSIONS, COMMUNITY_PHOTOS }
